"""set column unique

Revision ID: 036227015bfa
Revises: cde92de99f9e
Create Date: 2023-06-12 10:13:37.924090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036227015bfa'
down_revision = 'cde92de99f9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permission', ['perm_name'])
    op.create_unique_constraint(None, 'permission', ['perm_rule'])
    op.create_unique_constraint(None, 'role', ['role_name'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'permission', type_='unique')
    op.drop_constraint(None, 'permission', type_='unique')
    # ### end Alembic commands ###
