"""add user model

Revision ID: 442b3a4db116
Revises: 5bc68ea3883e
Create Date: 2023-05-01 18:18:27.956147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442b3a4db116'
down_revision = '5bc68ea3883e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
