"""add user model

Revision ID: 702573048713
Revises: bcd3bd9a12ac
Create Date: 2023-05-05 22:37:52.609708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702573048713'
down_revision = 'bcd3bd9a12ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
